analyze_image:
  name: Analyze Image
  description: "Send an image to Ollama for analysis and create a sensor with the result."
  fields:
    image_url:
      name: Image URL
      description: URL of the image to analyze
      required: true
      example: "https://example.com/image.jpg"
      selector:
        text:
    prompt:
      name: Prompt
      description: Prompt to send to Ollama with the image
      required: true
      example: "Describe what you see in this image in detail"
      selector:
        text:
    image_name:
      name: Image Name
      description: Unique name for this image (used for sensor naming)
      required: true
      example: "front_door_camera"
      selector:
        text:
    integration_id:
      name: Integration ID
      description: ID of the specific Ollama Vision integration to use (find it in the info sensor)
      required: false
      example: "abcd1234"
      selector:
        text: