analyze_image:
  name: "Analyze Image"
  description: "Send an image to Ollama for analysis and create a sensor with the result. Optionally elaborate the description with a text model."
  fields:
    image_url:
      name: "Image URL"
      description: "URL of the image to analyze"
      required: true
      example: "https://example.com/image.jpg"
      selector:
        text:
    prompt:
      name: "Vision Prompt"
      description: "Prompt to send to Ollama vision model with the image"
      required: false
      default: "This image is from a security camera above my front door. If there is a person in focus, describe the gender, estimated age, facial expression (mood), hairstyle, notable facial features, and clothing style clearly and concisely. If not, describe what is there clearly and concisely."
      selector:
        text:
    image_name:
      name: "Image Name"
      description: "Unique name for this image (used for sensor naming)"
      required: true
      example: "front_door_camera"
      selector:
        text:
    device_id:
      name: "Device ID"
      description: "ID of the specific Ollama Vision device to use"
      required: false
      selector:
        device:
          integration: ollama_vision
    use_text_model:
      name: "Use Text Model"
      description: "Whether to use the text model to elaborate on the vision model's description"
      required: false
      default: false
      selector:
        boolean:
    text_prompt:
      name: "Text Prompt"
      description: "Prompt template for the text model. Use \\{description\\} to reference the vision model's output."
      required: false
      default: "Given the following brief description of what is at my front door: {description}. If it is a person, create a short, humorous roast about their appearance or style. Keep it playful, harmless. If it is something else, describe it. Make it in Norwegian and keep it to less than 300 characters."
      selector:
        text: 
