generate_image_description:
  description: Sends an image URL to Ollama for description generation.
  fields:
    image_url:
      description: "URL of the image to describe"
      example: "http://homeassistant.local:8123/api/frigate/notifications/<id>/thumbnail.jpg"
    image_name:
      description: "A static alias of the image url used to store the latest state of the image, typically the name of the camera that is the source of a screenshot."
      example: "veranda"
    prompt:
      description: "Prompt to use for the description generation"
      example: "This image is from a security camera located above a door. Describe the gender, age, mood, hair style and the clothes of the person in this image."